services:
  employeetrackingsystemverticalslicingwithcqrs:
    image: ${DOCKER_REGISTRY-}employeetrackingsystemverticalslicingwithcqrs
    build:
      context: .
      dockerfile: EmployeeTrackingSystemVerticalSlicingWithCQRS/Dockerfile      
    ports:
        - "8080:8080"
        - "8081:8081"
    #configs:
    #  - source: appsettings.Development.json
    networks:
       - EmployeeTrackingSystemVerticalSlicingWithCQRS
    depends_on:
      - db
    
   
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Asd123456789@"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
       - EmployeeTrackingSystemVerticalSlicingWithCQRS

networks:
  EmployeeTrackingSystemVerticalSlicingWithCQRS:
    driver: bridge